const fs=require("fs"),path=require("path");
const ROOT=path.resolve(__dirname,"..");
const CAPYSVG=path.join(ROOT,"assets/capybaras"), ANIMALS=path.join(ROOT,"assets/animals");
const ORDER=["capybara","duck","puppy","kitten"], LABEL={capybara:"Capybara",duck:"Duck",puppy:"Puppy",kitten:"Kitten"};
const J=v=>JSON.stringify(v);
const svgBucket=f=>/(_|\b)wide(_|\b)/i.test(f)?"wide":/(_|\b)tall(_|\b)/i.test(f)?"tall":"square";
function svgFor(name){
  const b={square:[],portrait:[],wide:[],tall:[]};
  const dir=name==="capybara"?CAPYSVG:path.join(ANIMALS,name);
  const files=fs.existsSync(dir)?fs.readdirSync(dir).filter(f=>f.endsWith(".svg")).sort():[];
  for(const f of files) b[svgBucket(f)].push(fs.readFileSync(path.join(dir,f),"utf8").replace(/\n\s*/g,"").trim());
  return b;
}
function photosFor(name){
  const dir=path.join(ROOT,"photos",name); const out=[];
  if(fs.existsSync(dir)) for(const f of fs.readdirSync(dir).filter(f=>/\.(jpg|jpeg|png)$/i.test(f)).sort()){
    const m=f.match(/(\d+)x(\d+)/); if(!m) continue;
    out.push({u:"photos/"+name+"/"+f, ar:+(+m[1]/+m[2]).toFixed(4)});
  }
  return out;
}
const arr=a=>`[${a.map(J).join(",")}]`;
const photosJS=a=>`[${a.map(p=>`{u:${J(p.u)},ar:${p.ar}}`).join(",")}]`;
const svgJS=b=>`{ square:${arr(b.square)}, portrait:${arr(b.portrait)}, wide:${arr(b.wide)}, tall:${arr(b.tall)} }`;
const block=n=>`  { name:${J(n)}, label:${J(LABEL[n])}, photos:${photosJS(photosFor(n))}, svg:${svgJS(svgFor(n))} },`;

const out=`// animals.js: the photo library + slot-matching logic. Auto-generated by
// tools/build_animals.js; do not edit by hand. Each photo carries its aspect
// ratio (cropped at a real IAB size). pickFromTheme matches a slot to a photo
// of the same shape and covers it; for in-between shapes it picks a same-side
// photo so a crop trims background, not the animal.

const ANIMAL_THEMES = [
${ORDER.map(block).join("\n")}
];
const AR_TOL = 0.12; // relative aspect tolerance for matching a photo to a slot
function themeHasAssets(t){ const s=t.svg; return t.photos.length || s.square.length||s.portrait.length||s.wide.length||s.tall.length; }
function activeThemes(){ return ANIMAL_THEMES.filter(themeHasAssets); }
const SVG_FALLBACK={ wide:["wide","square"], tall:["tall","portrait","square"], portrait:["portrait","tall","square"], square:["square","portrait"] };
function pickFromTheme(theme,w,h){
  const rnd=a=>a[Math.floor(Math.random()*a.length)];
  const slotAr=(w&&h)?w/h:1;
  const P=theme.photos;
  if(P.length){
    const close=P.filter(p=>Math.abs(p.ar-slotAr)/slotAr<=AR_TOL);
    if(close.length) return {kind:"photo",data:rnd(close).u,fit:"cover"}; // shapes match: full bleed, no bad crop
    // No exact-aspect photo. Prefer a photo on the SAME SIDE as the slot; a
    // wider photo for a wide slot, a taller photo for a tall slot, so a cover
    // crop trims background (the generous margins we shoot for), never the
    // animal's head/feet. Cover when the nearest such photo is within COVER_MAX;
    // only a wild mismatch with nothing safe on that side letterboxes on cream.
    const COVER_MAX=0.70;
    const sameSide=P.filter(p=> slotAr>=1 ? p.ar>=slotAr : p.ar<=slotAr);
    const cands=sameSide.length?sameSide:P;
    let best=cands[0],bd=Infinity; for(const p of cands){const d=Math.abs(Math.log(p.ar/slotAr)); if(d<bd){bd=d;best=p;}}
    return {kind:"photo",data:best.u,fit: bd<=COVER_MAX ? "cover" : "contain"};
  }
  const b= slotAr>=2.2?"wide": slotAr<=0.45?"tall": slotAr<=0.7?"portrait":"square";
  for(const k of SVG_FALLBACK[b]) if(theme.svg[k].length) return {kind:"svg",data:rnd(theme.svg[k])};
  return {kind:"svg",data:"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1 1'></svg>"};
}
`;
fs.writeFileSync(path.join(ROOT,"animals.js"),out);
console.log("animals.js:",(fs.statSync(path.join(ROOT,"animals.js")).size/1024).toFixed(1),"KB; capybara photos:",photosFor("capybara").length);
